default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: hello_rails_newapp_back_end_development
  username: postgres
  password: kingno3l

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: hello_rails_newapp_back_end_production
